### ISSUE TITLE
Fix: Contact Us UI Page overflow

### ISSUE THREAD

**Issue by Girishbari** [HITK-TECH-Community/Community-Website#833]
**Describe the bug**
In Dashborad some pages like contact us, join us  overflows due to some CSS issue 

**Screenshots**
![image](https://github.com/HITK-TECH-Community/Community-Website/assets/38005544/29664d39-0fa8-4ecb-8f12-6aeea68ea70e)

![image](https://github.com/HITK-TECH-Community/Community-Website/assets/38005544/aa3ed819-23d4-4b59-89c0-ac88eed17e9f)

**Desktop (please complete the following information):**
 - OS: 
 - Browser [chrome, safari]

**Additional context**

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Write your answer here. yes I am aware of it

**Comment by Girishbari** [comment]
assign it to me

**Comment by Kajol-Kumari** [comment]
@Girishbari  please make sure the uI is responsive for all the screen including mobile devices. Happy Learning :)

**Comment by Girishbari** [comment]
I am constantly getting this errors while doing **npm install**, I did try `--force and --legacy-deps` but it does not seems to work
```
npm ERR! Building: C:\Program Files\nodejs\node.exe C:\Users\barig\swoc\Community-Website\frontend\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm ERR! gyp verb cli   'C:\\Users\\barig\\swoc\\Community-Website\\frontend\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@20.10.0 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\barig\swoc\Community-Website\frontend\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Users\barig\swoc\Community-Website\frontend\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Users\barig\swoc\Community-Website\frontend\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Users\barig\swoc\Community-Website\frontend\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Users\barig\swoc\Community-Website\frontend\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Users\barig\swoc\Community-Website\frontend\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:199:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\barig\swoc\Community-Website\frontend\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Users\barig\swoc\Community-Website\frontend\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Users\barig\swoc\Community-Website\frontend\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Users\barig\swoc\Community-Website\frontend\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Users\barig\swoc\Community-Website\frontend\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Users\barig\swoc\Community-Website\frontend\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:199:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` succeeded python C:\Users\barig\AppData\Local\Programs\Python\Python312\python.EXE
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Command failed: C:\Users\barig\AppData\Local\Programs\Python\Python312\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
npm ERR! gyp ERR! stack SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?   
npm ERR! gyp ERR! stack
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:422:12)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:514:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1105:16)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
npm ERR! gyp ERR! System Windows_NT 10.0.22631
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\barig\\swoc\\Community-Website\\frontend\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd C:\Users\barig\swoc\Community-Website\frontend\node_modules\node-sass
npm ERR! gyp ERR! node -v v20.10.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1
```
